name: Run Bot

# Trigger the workflow on push or pull_request events to main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # You can adjust the version here

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install Python dependencies from your requirements.txt file
          sudo apt install ffmpeg

      # Step 4: Run the bot
      - name: Run bot
        run: |
          python bot.py  # Replace this with the command to start your bot
